export * as A from './Array'
export * as AP from './Apply'
export * as E from './Either'
export * as J from './Json'
export * as NEA from './NonEmptyArray'
export * as O from './Option'
export * as P from './Promise'
export * as R from './Record'
export * as Semi from './Semigroup'
export * as S from './String'
export * as T from './Task'
export * as TE from './TaskEither'
export * from './function'
