export { Eq, isNumber, MonoidProduct, MonoidSum, Ord } from 'fp-ts/number'
export {
  add,
  BoundedSafe,
  decrement,
  digits,
  divide,
  EnumInt,
  floatFromString,
  fromString,
  fromStringWithRadix,
  increment,
  integerFromString,
  isFinite,
  isNegative,
  isNonNegative,
  isNonPositive,
  isPositive,
  isValid,
  mod,
  multiply,
  negate,
  rem,
  subtract,
  toFinite,
} from 'fp-ts-std/Number'
